services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      DATABASE_URL: mysql://root:4Fggjdkj44343dfdjfk@echtz_db:3306/test?serverVersion=mariadb-10.3.36&charset=utf8mb4
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
  echtz_db:
    container_name: echtz_2_db
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=4Fggjdkj44343dfdjfk
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - ./data:/var/lib/mysql
    ports:
      - ${ECHZEIT_DB_PORT:-3431}:3306

  echtz_phpmyadmin:
    container_name: echtz_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - ${ECHZEIT_PMA_PORT:-3432}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=echtz_db
      - PMA_USER=root
      - PMA_PASSWORD=4Fggjdkj44343dfdjfk
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 2


volumes:
  caddy_data:
  caddy_config:

